sudo: required

services:
  - docker

before_install:
  - docker build -t rahulbarick/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahulbarick/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-246802837414"
  bucket_path: "docker-react"
  on:
    branch: master
  edge: true
  
  # session_token: $AWS_SESSION_TOKEN